version: "3"
services:
    rabbitmq_server:
        image: rabbitmq:3-management
        ports: 
            - "8080:15672"
        environment: 
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: password